bucket_name = "vprofile-al-ops"
aws_region = "us-east-1"
elb_sg = "vprofile-ELB-SG"
app_sg = "vprofile-APP-SG"
backend_sg = "vprofile-BACKEND-SG"
instance_type = "t2.micro"
db_instance_name = "vprofile-db01"
mc_instance_name = "vprofile-mc01"
rmq_instance_name = "vprofile-rmq01"
app_instance_name = "vprofile-app01"
centos_ami_name = "CentOS-Stream-*9*"
ubuntu_ami_name = "*ubuntu-jammy-22*"
key_pair_name = "vprofile_prod_key"
project = "vprofile"

