---
- name: Install Elastic Agent on EC2 instances
  hosts: all
  become: yes
  tasks:
    - name: Check if Elastic Agent is running
      shell: pgrep elastic-agent
      register: elastic_agent_check
      failed_when: false
      changed_when: false

    - name: Download Elastic Agent
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.9.2-linux-x86_64.tar.gz"
        dest: "/tmp/elastic-agent-8.9.2-linux-x86_64.tar.gz"
      when: elastic_agent_check.rc != 0

    - name: Extract Elastic Agent
      unarchive:
        src: "/tmp/elastic-agent-8.9.2-linux-x86_64.tar.gz"
        dest: "/tmp"
        remote_src: yes
      when: elastic_agent_check.rc != 0

    - name: Install Elastic Agent
      command:
        cmd: "./elastic-agent install -n --url={{ elastic_url }} --enrollment-token={{ enrollment_token }}"
        chdir: "/tmp/elastic-agent-8.9.2-linux-x86_64"
      when: elastic_agent_check.rc != 0

